language: php
php:
  - '7.2'

# From PHPUnit's config
install:
  - travis_retry composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - composer phpunit
  - composer phpstan
  - composer phpcs

after_success:
    - bash <(curl -s https://codecov.io/bash)
